INT_SCALE = 1024
PERCENT = 100
PERCENT_SCALE = 10000

LEVEL = 120
LEVEL_SCALE = 450
LEVEL_CONSTANT = 45750

DAMAGE_SCALE = 16
DOT_DAMAGE_SCALE = 12 * DAMAGE_SCALE * DAMAGE_SCALE
PHYSICAL_DAMAGE_SCALE = 10

MAX_GCD_GROUP = 10

CRITICAL_STRIKE_SCALE = 9.530 * (LEVEL_SCALE * LEVEL - LEVEL_CONSTANT)
CRITICAL_DAMAGE_SCALE = 3.335 * (LEVEL_SCALE * LEVEL - LEVEL_CONSTANT)
OVERCOME_SCALE = 9.530 * (LEVEL_SCALE * LEVEL - LEVEL_CONSTANT)
HASTE_SCALE = 11.695 * (LEVEL_SCALE * LEVEL - LEVEL_CONSTANT)
STRAIN_SCALE = 9.189 * (LEVEL_SCALE * LEVEL - LEVEL_CONSTANT)
SURPLUS_SCALE = 13.192

SHIELD_SCALE = 5.091

MAJOR_BASE = 179
WEAPON_DAMAGE_BASE = 540
ATTACK_POWER_BASE = 360
MINOR_BASE = 799

CRITICAL_DAMAGE_BASE = 1.75

AGILITY_TO_CRITICAL_STRIKE = 655 / INT_SCALE
STRENGTH_TO_ATTACK_POWER = 153 / INT_SCALE
STRENGTH_TO_OVERCOME = 307 / INT_SCALE
SPIRIT_TO_CRITICAL_STRIKE = 655 / INT_SCALE
SPUNK_TO_ATTACK_POWER = 184 / INT_SCALE
SPUNK_TO_OVERCOME = 307 / INT_SCALE
